### ISSUE TITLE
ValueError: cannot reshape array of size 1018982156 into shape (2,300000,1,64,64)

### ISSUE THREAD

**Issue by Llululu** [Hzzone/DU-GAN#3]
你好，师兄。我在复现你工作的时候，出现了这个问题。
 File "/media/data/sdd_d/yyc/DU-GAN-master/utils/dataset.py", line 12, in __init__
    data = torch.from_numpy(np.load(npy_root).astype(np.float32) - 1024)
错误显示在这里，恳请处理方法！

**Comment by piarosebelledelapaz** [comment]
hello, how did you fix the error?
