### ISSUE TITLE
testing the model 

### ISSUE THREAD

**Issue by Tihetna1891** [Hzzone/DU-GAN#4]
is the testing also done parallely using the training shell

**Comment by Hzzone** [comment]
see https://github.com/Hzzone/DU-GAN/blob/308d6d0d858559c29282de915a3945d2240627e6/models/DUGAN/DUGAN.py#L214

**Comment by Tihetna1891** [comment]
thanks , and can you tell me how do you prepare the csv files of the datasets and if there is any code for preparing them please share it to me
