### ISSUE TITLE
about training  hyper-parameters

### ISSUE THREAD

**Issue by Tihetna1891** [Hzzone/DU-GAN#8]
hey, could you please explain to me that how can I represent the training hyper-parameters in terms of epoch because in the paper its mentioned that "During training, we trained the model with a maximum
of 100K iterations and with a mini-batch of size 64 " so that means number of iterations are equal to number of epoch ?
thanks

**Comment by Hzzone** [comment]
You should first understand the concept of `epoch` and `iteration`. The number of iterations here is a predefined hyperparameter, invariant to epoch.
